CREATE TABLE IF NOT EXISTS category (
id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(50) NOT NULL UNIQUE,
parent_id BIGINT,
CONSTRAINT parent_category_fk FOREIGN KEY (parent_id) REFERENCES category(id)
);

CREATE TABLE IF NOT EXISTS product (
id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(50) NOT NULL UNIQUE,
price DOUBLE NOT NULL,
currency VARCHAR(50) NOT NULL,
category_id BIGINT,
CONSTRAINT category_fk FOREIGN KEY (category_id) REFERENCES category(id)
);
